version: '3.8'

services:
  app:
    image: archiveium/archiveium:latest
    ports:
      - '5292:80'
    volumes:
      - app_storage:/var/www/html/storage
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/login"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - archiveium_prod
    depends_on:
      - db

  queue_default:
    image: archiveium/archiveium:latest
    volumes:
      - app_storage:/var/www/html/storage
      - ./docker/prod/conf.d/docker-php-memory-limit.ini:/usr/local/etc/php/conf.d/docker-php-memory-limit.ini
    environment:
      - CONTAINER_ROLE=queue
      - QUEUE_NAME=default
    env_file:
      - .env
    networks:
      - archiveium_prod
    depends_on:
      - db

  queue_listeners:
    image: archiveium/archiveium:latest
    volumes:
      - app_storage:/var/www/html/storage
    environment:
      - CONTAINER_ROLE=queue
      - QUEUE_NAME=listeners
    env_file:
      - .env
    networks:
      - archiveium_prod
    depends_on:
      - db

  scheduler:
    image: archiveium/archiveium:latest
    volumes:
      - app_storage:/var/www/html/storage
    environment:
      - CONTAINER_ROLE=scheduler
    env_file:
      - .env
    networks:
      - archiveium_prod
    depends_on:
      - db

  db:
    image: 'postgres:13'
    ports:
      - '5432:5432'
    environment:
      PGPASSWORD: "$DB_PASSWORD"
      POSTGRES_DB: "$DB_DATABASE"
      POSTGRES_USER: "$DB_USERNAME"
      POSTGRES_PASSWORD: "$DB_PASSWORD"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - archiveium_prod
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
      retries: 3
      timeout: 5s

volumes:
  db_data:
  app_storage:

networks:
  archiveium_prod:
    name: archiveium_prod
