version: '3.8'

services:
  app:
    image: archiveium/frontend:0.0.17
    ports:
      - 5292:3000
    volumes:
      - ./frontend.json:/app/config/production-0.json
    environment:
      TZ: 'America/Toronto'   # Change timezone as needed
      NODE_APP_INSTANCE: 0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/login"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - archiveium
      # Enable if running behind Traefik
      # - traefik
    depends_on:
      - db
      - redis
      - minio
    # Enable if running behind Traefik
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.archiveium.rule=Host(`URL_HERE`)"
    #   - "traefik.http.routers.archiveium.entrypoints=websecure"
    #   - "traefik.http.routers.archiveium.tls.certresolver=cloudflare"
    #   - "traefik.http.services.archiveium.loadbalancer.server.port=3000"

  cron:
    image: archiveium/frontend:0.0.17
    volumes:
      - ./frontend.json:/app/config/production-0.json
    environment:
      TZ: 'America/Toronto'       # Change timezone as needed
      NODE_APP_INSTANCE: 0
      USE_AS_CRON_PROCESSOR: true # Needed to run container as cron job processor
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/login"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - archiveium
    depends_on:
      - app
      - db
      - minio

  db:
    image: postgres:13
    # ports:
    #   - 5432:5432
    environment:
      PGPASSWORD: "$DB_PASSWORD"          # Should be the same as that of app
      POSTGRES_DB: "$DB_DATABASE"         # Should be the same as that of app
      POSTGRES_USER: "$DB_USERNAME"       # Should be the same as that of app
      POSTGRES_PASSWORD: "$DB_PASSWORD"   # Should be the same as that of app
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - archiveium
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
      retries: 3
      timeout: 5s

  minio:
    image: 'minio/minio:RELEASE.2022-09-25T15-44-53Z'
    # ports:
    #   - 9000:9000
    environment:
      MINIO_ROOT_USER: '$MINIO_USER'            # Should be the same as that of app
      MINIO_ROOT_PASSWORD: '$MINIO_PASSWORD'    # Should be the same as that of app
      MINIO_COMPRESSION_ENABLE: 'on'
      MINIO_COMPRESSION_EXTENSIONS: ''
      MINIO_COMPRESSION_MIME_TYPES: ''
    volumes:
      - minio_data:/data/minio
    networks:
      - archiveium
    entrypoint: sh
    command: -c 'mkdir -p /data/minio/emails && minio server /data/minio'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      retries: 3
      timeout: 5s

  redis:
    image: 'redis:7.0.10-alpine'
    mem_limit: 128M
#    ports:
#      - '6379:6379'
    command: redis-server --maxmemory-policy noeviction --appendonly yes --maxmemory 200M
    volumes:
      - redis_data:/data
    networks:
      - archiveium

volumes:
  db_data:
  minio_data:
  redis_data:

networks:
  archiveium:
  # Enable if running behind Traefik
  # traefik:
  #   external: true