version: '2'

services:
  frontend:
    image: 'node:16.17.1'
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
    networks:
      - frontend
  db:
    image: 'postgres:13'
    ports:
      - '5432:5432'
    environment:
      PGPASSWORD: 'archiveiumPassword'
      POSTGRES_DB: 'archiveium'
      POSTGRES_USER: 'archiveium'
      POSTGRES_PASSWORD: 'archiveiumPassword'
    volumes:
      - 'db:/var/lib/postgresql/data'
    networks:
      - frontend
  redis:
    image: 'redis:7.0.10-alpine'
    ports:
      - '6379:6379'
    command: redis-server --maxmemory-policy noeviction --appendonly yes --maxmemory 200M
    volumes:
      - 'cache:/data'
    networks:
      - frontend
  mailpit:
    image: 'axllent/mailpit:v1.9.10'
    environment:
      - MP_SMTP_BIND_ADDR=0.0.0.0:1029
      - MP_UI_BIND_ADDR=0.0.0.0:8029
    ports:
      - 1029:1029
      - 8029:8029
    networks:
      - frontend

networks:
  frontend:

volumes:
  db:
  cache:
