name: Archiveium Frontend

on:
  push:
    branches: ['main', 'beta']
  pull_request:
    branches: ['main', 'beta']
  workflow_dispatch:

jobs:
  #   lint:
  #     name: Lint
  #     runs-on: ubuntu-latest
  #     steps:
  #       - name: Checkout Repository
  #         uses: actions/checkout@v3
  #       - name: Use Node.js 16.x
  #         uses: actions/setup-node@v3
  #         with:
  #           node-version: 16.x
  #           cache: 'npm'
  #       - run: npm ci
  #       - run: npm run lint

  build:
    name: Build
    # needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci
      # env values passed here are to ensure build step in Github does not fail
      # Remove once there's a resolution https://github.com/sveltejs/kit/discussions/7265
      - env:
          LOG_LEVEL: ''
        run: npm run build

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci
      - run: npm run test:unit
      - run: npm run test:coverage
      - name: Coverage Report
        if: always() # generate the report if tests are failing
        uses: davelosert/vitest-coverage-report-action@v1

  release-prod:
    name: Release Prod
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci
      - env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm run release:prod

  release-beta:
    name: Release Beta
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/beta'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: beta
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci
      - env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm run release:beta

  docker-beta:
    name: Build & Push Beta Docker Image
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/beta'
    needs: release-beta
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: beta
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set Release Version
        run: |
          version=$(node -p "require('./package.json').version")
          echo "RELEASE_VERSION=$version" >> $GITHUB_ENV
      - name: Push to Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: |-
            linux/amd64
            linux/arm64
          file: Dockerfile
          push: true
          tags: archiveium/frontend:${{ env.RELEASE_VERSION }}

  docker-prod:
    name: Build & Push Prod Docker Image
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: release-prod
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set Release Version
        run: |
          version=$(node -p "require('./package.json').version")
          echo "RELEASE_VERSION=$version" >> $GITHUB_ENV
      - name: Push to Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: |-
            linux/amd64
            linux/arm64
          file: Dockerfile
          push: true
          tags: archiveium/frontend:${{ env.RELEASE_VERSION }},archiveium/frontend:latest

  trigger:
    name: Update deployer
    needs: docker-prod
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: Get Release Version
        run: |
          version=$(node -p "require('./package.json').version")
          echo "RELEASE_VERSION=$version" >> $GITHUB_ENV
      - name: Trigger Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'archiveium',
              repo: 'deployer',
              workflow_id: 'main.yml',
              ref: 'main',
              inputs: {
                frontendVersion: '${{ env.RELEASE_VERSION }}'
              },
            })
